#!/usr/bin/env bash

THIS_DIR="${0%/*}"
DB_NAME=$("${THIS_DIR}"/database-name)

CSV_SEED_DIR="./database/csv_seed"

echo "load: ${CSV_SEED_DIR}/assignee_enum.csv => assignee_enum"

docker exec -it "${DB_NAME}" psql -U postgres -c "\copy assignee_enum \
(assignee_enum) \
from ${CSV_SEED_DIR}/assignee_enum.csv delimiter ',' csv header;"
