#!/usr/bin/env bash

THIS_DIR="${0%/*}"
DB_NAME=$("${THIS_DIR}"/database-name)

CSV_SEED_DIR="./database/csv_seed"

echo "load: ${CSV_SEED_DIR}/task.csv => task"

docker exec -it "${DB_NAME}" psql -U postgres -c "\copy task \
(task,assignee_enum_id,due_date,status_enum_id) \
from ${CSV_SEED_DIR}/task.csv delimiter ',' csv header;"
