#!/usr/bin/env bash

try () {
    [ -f fatal.txt ] && cat fatal.txt && exit 1
    "$@" || exit 1
}

. appgen-venv
database-init # ensure baseline scripts
SCHEMA_DIR="${0%/*}/schema_json"

# ensure seed data can be found
CSV_DIR="${0%/*}/csv_raw"
generate() {
    # processes the csv files in ./csv
    # - generates json schemas in ./schema
    # - generates csv seed files in ./backend/database/csv_seed
    # - generates scripts in ./backend/database/scripts
    # - generates sql in ./backend/database/sql
    try raw-csv-to-schema "${CSV_DIR}/${1}.csv" --quiet
}
generate AssigneeEnum
generate StatusEnum
generate TaskFieldsEnum
generate Task
