#!/usr/bin/env bash

try () {
    [ -f fatal.txt ] && cat fatal.txt && exit 1
    "$@" || exit 1
}

try appgen
SCHEMA_DIR="${0%/*}/schema_json"
# ensure seed data can be found
"./${0%/*}/generate-schema"

# backend/api
# - generate API endpoint(s)
try api-endpoint-crud-schema "${SCHEMA_DIR}/assignee_enum.json"
try api-endpoint-crud-schema "${SCHEMA_DIR}/status_enum.json"
try api-endpoint-crud-schema "${SCHEMA_DIR}/task_fields_enum.json"
try api-endpoint-be4fe-paged-schema "${SCHEMA_DIR}/task.json" --entity-fields=task_fields_enum.json

# frontend
# - generate page(s) using schema
try app-page-enum-crud-schema "${SCHEMA_DIR}/assignee_enum.json"
try app-page-enum-crud-schema "${SCHEMA_DIR}/status_enum.json"
try app-page-enum-_ru_-schema "${SCHEMA_DIR}/task_fields_enum.json"
try app-page-table-be4fe-paged-schema "${SCHEMA_DIR}/task.json"

# amend menu item(s)
try app-menu-add --menu=Task
try app-menu-add --menu=Assignee
try app-menu-add --menu=Status
# app-menu-remove --menu=Home

# create db table(s) and seed them (allow time for db to become available)
try ./docker/db-start
echo "waiting for database..."
sleep 10s
try ./docker/db-seed
try ./docker/db-stop

echo
echo "app configured"
echo "./docker/app-start"
echo "./app-start"
echo "http://localhost:4200"
echo "http://localhost:3000/api-docs"
